package evidence

import "testing"

// TestAgentLifecycleEventsAreCatalogued guards the two agent lifecycle names: they
// must be in the Catalog (so the recorder accepts them) and Validate must pass, or
// the controller could never emit an agent.started/agent.completed.
func TestAgentLifecycleEventsAreCatalogued(t *testing.T) {
	for _, name := range []string{EventAgentStarted, EventAgentCompleted} {
		if !Catalog[name] {
			t.Errorf("event %q missing from Catalog", name)
		}
		ev := Event{Name: name, Class: ClassIntegrity, Outcome: OutcomeSuccess}
		if err := ev.Validate(); err != nil {
			t.Errorf("Validate(%q) = %v, want nil", name, err)
		}
	}
}

// TestAgentIDDerivationVectors pins the deterministic id derivation to
// independently-computed known answers. The vectors were generated by hashing the
// literal preimage "boxedai.agent/v1|<session>|<scope>|<native>" outside this
// package, so a change to the domain separator or preimage layout breaks the test
// rather than silently reassigning every agent's id.
func TestAgentIDDerivationVectors(t *testing.T) {
	const session = "bx-test-session"
	cases := []struct {
		name string
		got  string
		want string
	}{
		{"primary", PrimaryAgentID(session), "ag-6cb65af7afed9fcc"},
		{"child task-42", ChildAgentID(session, "task-42"), "ag-07aa8ee7ac9bd424"},
		{"child = session id", ChildAgentID(session, session), "ag-bd297ca3ae95e648"},
	}
	for _, c := range cases {
		if c.got != c.want {
			t.Errorf("%s id = %q, want %q", c.name, c.got, c.want)
		}
	}
}

// TestAgentIDsAreDeterministic asserts the derivations are pure functions of their
// inputs: the verifier recomputes ids offline from the segment stream and must land
// on the exact bytes the controller and hook produced.
func TestAgentIDsAreDeterministic(t *testing.T) {
	if PrimaryAgentID("s") != PrimaryAgentID("s") {
		t.Error("PrimaryAgentID is not deterministic")
	}
	if ChildAgentID("s", "n") != ChildAgentID("s", "n") {
		t.Error("ChildAgentID is not deterministic")
	}
}

// TestPrimaryAndChildIDsNeverCollide is the reason the derivation carries a scope
// token: a Child Agent whose native id happens to equal the session id must not
// mint the Primary Agent's id, or a subagent could impersonate the controller-owned
// root of the hierarchy.
func TestPrimaryAndChildIDsNeverCollide(t *testing.T) {
	const session = "bx-collision"
	if PrimaryAgentID(session) == ChildAgentID(session, session) {
		t.Error("child with native_id == session collided with the Primary Agent id")
	}
}

// TestAgentIDsDependOnEveryInput proves session and native id both feed the digest,
// so distinct agents in distinct sessions never share an id.
func TestAgentIDsDependOnEveryInput(t *testing.T) {
	if PrimaryAgentID("s1") == PrimaryAgentID("s2") {
		t.Error("primary id ignored the session id")
	}
	if ChildAgentID("s", "n1") == ChildAgentID("s", "n2") {
		t.Error("child id ignored the native id")
	}
	if ChildAgentID("s1", "n") == ChildAgentID("s2", "n") {
		t.Error("child id ignored the session id")
	}
}

// TestAgentAttributionForChannel locks the security-critical mapping the recorder
// uses to stamp method/strength from the authenticated channel. Only the controller
// earns strong; a workload's self-report is native_harness/self_reported; every
// other channel (and any unknown one) is unattributed/none — a workload event can
// never present as controller/strong.
func TestAgentAttributionForChannel(t *testing.T) {
	cases := []struct {
		ch           Channel
		wantMethod   AttributionMethod
		wantStrength AttributionStrength
	}{
		{ChannelController, MethodController, StrengthStrong},
		{ChannelWorkload, MethodNativeHarness, StrengthSelfReported},
		{ChannelBroker, MethodUnattributed, StrengthNone},
		{ChannelGuestSupervisor, MethodUnattributed, StrengthNone},
		{ChannelRecorder, MethodUnattributed, StrengthNone},
		{Channel("smuggled"), MethodUnattributed, StrengthNone},
	}
	for _, c := range cases {
		method, strength := AgentAttributionFor(c.ch)
		if method != c.wantMethod || strength != c.wantStrength {
			t.Errorf("AgentAttributionFor(%q) = %q/%q, want %q/%q",
				c.ch, method, strength, c.wantMethod, c.wantStrength)
		}
	}
}
