package evidence

import (
	"testing"
	"time"
)

// TestAgentLifecycleEventsAreCatalogued guards the two agent lifecycle names: they
// must be in the Catalog (so the recorder accepts them) and Validate must pass, or
// the controller could never emit an agent.started/agent.completed.
func TestAgentLifecycleEventsAreCatalogued(t *testing.T) {
	for _, name := range []string{EventAgentStarted, EventAgentCompleted} {
		if !Catalog[name] {
			t.Errorf("event %q missing from Catalog", name)
		}
		ev := Event{Name: name, Class: ClassIntegrity, Outcome: OutcomeSuccess}
		if err := ev.Validate(); err != nil {
			t.Errorf("Validate(%q) = %v, want nil", name, err)
		}
	}
}

// TestAgentIDDerivationVectors pins the deterministic id derivation to
// independently-computed known answers. The vectors were generated by hashing the
// literal preimage "boxedai.agent/v1|<session>|<scope>|<native>" outside this
// package, so a change to the domain separator or preimage layout breaks the test
// rather than silently reassigning every agent's id.
func TestAgentIDDerivationVectors(t *testing.T) {
	const session = "bx-test-session"
	cases := []struct {
		name string
		got  string
		want string
	}{
		{"primary", PrimaryAgentID(session), "ag-6cb65af7afed9fcc"},
		{"child task-42", ChildAgentID(session, "task-42"), "ag-07aa8ee7ac9bd424"},
		{"child = session id", ChildAgentID(session, session), "ag-bd297ca3ae95e648"},
	}
	for _, c := range cases {
		if c.got != c.want {
			t.Errorf("%s id = %q, want %q", c.name, c.got, c.want)
		}
	}
}

// TestAgentIDsAreDeterministic asserts the derivations are pure functions of their
// inputs: the verifier recomputes ids offline from the segment stream and must land
// on the exact bytes the controller and hook produced.
func TestAgentIDsAreDeterministic(t *testing.T) {
	if PrimaryAgentID("s") != PrimaryAgentID("s") {
		t.Error("PrimaryAgentID is not deterministic")
	}
	if ChildAgentID("s", "n") != ChildAgentID("s", "n") {
		t.Error("ChildAgentID is not deterministic")
	}
}

// TestPrimaryAndChildIDsNeverCollide is the reason the derivation carries a scope
// token: a Child Agent whose native id happens to equal the session id must not
// mint the Primary Agent's id, or a subagent could impersonate the controller-owned
// root of the hierarchy.
func TestPrimaryAndChildIDsNeverCollide(t *testing.T) {
	const session = "bx-collision"
	if PrimaryAgentID(session) == ChildAgentID(session, session) {
		t.Error("child with native_id == session collided with the Primary Agent id")
	}
}

// TestAgentIDsDependOnEveryInput proves session and native id both feed the digest,
// so distinct agents in distinct sessions never share an id.
func TestAgentIDsDependOnEveryInput(t *testing.T) {
	if PrimaryAgentID("s1") == PrimaryAgentID("s2") {
		t.Error("primary id ignored the session id")
	}
	if ChildAgentID("s", "n1") == ChildAgentID("s", "n2") {
		t.Error("child id ignored the native id")
	}
	if ChildAgentID("s1", "n") == ChildAgentID("s2", "n") {
		t.Error("child id ignored the session id")
	}
}

// TestAgentAttributionForChannel locks the security-critical mapping the recorder
// uses to stamp method/strength from the authenticated channel. Only the controller
// earns strong; a workload's self-report is native_harness/self_reported; every
// other channel (and any unknown one) is unattributed/none — a workload event can
// never present as controller/strong.
func TestAgentAttributionForChannel(t *testing.T) {
	cases := []struct {
		ch           Channel
		wantMethod   AttributionMethod
		wantStrength AttributionStrength
	}{
		{ChannelController, MethodController, StrengthStrong},
		{ChannelWorkload, MethodNativeHarness, StrengthSelfReported},
		{ChannelBroker, MethodUnattributed, StrengthNone},
		{ChannelGuestSupervisor, MethodUnattributed, StrengthNone},
		{ChannelRecorder, MethodUnattributed, StrengthNone},
		{Channel("smuggled"), MethodUnattributed, StrengthNone},
	}
	for _, c := range cases {
		method, strength := AgentAttributionFor(c.ch)
		if method != c.wantMethod || strength != c.wantStrength {
			t.Errorf("AgentAttributionFor(%q) = %q/%q, want %q/%q",
				c.ch, method, strength, c.wantMethod, c.wantStrength)
		}
	}
}

// TestHumanMutationAttributionRequiresASealedActiveGrant locks the no-promotion
// boundary for the UID split used by the mediated workspace. UID 5000 is not a
// human claim by itself: it becomes human only when it matches the immutable
// session subject map and a live, non-revoked controller grant.
func TestHumanMutationAttributionRequiresASealedActiveGrant(t *testing.T) {
	now := time.Date(2026, time.August, 18, 12, 0, 0, 0, time.UTC)
	subjects := SessionSubjectMap{
		SessionID: "bx-test-session",
		Subjects: []SessionSubject{
			{UID: WorkloadUID, ActorClass: MutationActorAgent},
			{UID: HumanUID, ActorClass: MutationActorHuman, SubjectID: "operator-1", GrantID: "grant-1"},
		},
	}
	grant := HumanAccessGrant{
		SessionID:        subjects.SessionID,
		GrantID:          "grant-1",
		SubjectID:        "operator-1",
		ExpiresAt:        now.Add(time.Minute),
		AllowedSurfaces:  []AccessSurface{AccessSurfaceBrowserTerminal},
		UID:              HumanUID,
		CredentialDigest: SHA256Hex([]byte("credential")),
	}

	for _, tc := range []struct {
		name  string
		uid   int64
		grant *HumanAccessGrant
		at    time.Time
		want  MutationActorClass
	}{
		{"workload uid is agent", WorkloadUID, &grant, now, MutationActorAgent},
		{"root uid is supervisor", 0, &grant, now, MutationActorSupervisor},
		{"active sealed human grant", HumanUID, &grant, now, MutationActorHuman},
		{"human uid without grant is unattributed", HumanUID, nil, now, MutationActorUnattributed},
		{"expired human grant is unattributed", HumanUID, &grant, grant.ExpiresAt, MutationActorUnattributed},
		{"other uid is unattributed", 6000, &grant, now, MutationActorUnattributed},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := MutationActorFor(tc.uid, subjects, tc.grant, tc.at); got != tc.want {
				t.Errorf("MutationActorFor(%d) = %q, want %q", tc.uid, got, tc.want)
			}
		})
	}
	if !subjects.AllowsMutation(WorkloadUID, &grant, MutationOperationWrite, now) {
		t.Fatal("workload mutation rejected by sealed operation gate")
	}
	if !subjects.AllowsMutation(0, &grant, MutationOperationMetadata, now) {
		t.Fatal("supervisor mutation rejected by sealed operation gate")
	}
	if subjects.AllowsMutation(6000, &grant, MutationOperationWrite, now) {
		t.Fatal("unknown uid accepted by sealed operation gate")
	}
}

// TestMutationActorForRecord locks the channel gate on the recorder's
// binding-aware classifier: only a guest-supervisor mutation can join the sealed
// human-access binding and promote to human/supervisor; every other channel — even
// carrying the identical valid binding — falls back to the channel-only
// classifier, so a workload cannot forge a human mutation on its own channel.
func TestMutationActorForRecord(t *testing.T) {
	now := time.Date(2026, time.August, 18, 12, 0, 0, 0, time.UTC)
	subjects := SessionSubjectMap{
		SessionID: "bx-test-session",
		Subjects: []SessionSubject{
			{UID: WorkloadUID, ActorClass: MutationActorAgent},
			{UID: HumanUID, ActorClass: MutationActorHuman, SubjectID: "operator-1", GrantID: "grant-1"},
		},
	}
	grant := HumanAccessGrant{
		SessionID:        subjects.SessionID,
		GrantID:          "grant-1",
		SubjectID:        "operator-1",
		ExpiresAt:        now.Add(time.Minute),
		AllowedSurfaces:  []AccessSurface{AccessSurfaceBrowserTerminal},
		UID:              HumanUID,
		CredentialDigest: SHA256Hex([]byte("credential")),
	}
	binding := &HumanAccessBinding{SubjectMap: subjects, Grant: grant}
	expiredGrant := grant
	expiredGrant.ExpiresAt = now.Add(-time.Minute)
	expiredBinding := &HumanAccessBinding{SubjectMap: subjects, Grant: expiredGrant}

	for _, tc := range []struct {
		name    string
		channel Channel
		uid     int64
		binding *HumanAccessBinding
		want    MutationActorClass
	}{
		{"guest-supervisor human uid with valid binding", ChannelGuestSupervisor, HumanUID, binding, MutationActorHuman},
		{"guest-supervisor workload uid with valid binding", ChannelGuestSupervisor, WorkloadUID, binding, MutationActorAgent},
		{"guest-supervisor root uid with valid binding", ChannelGuestSupervisor, 0, binding, MutationActorSupervisor},
		{"guest-supervisor human uid with expired grant", ChannelGuestSupervisor, HumanUID, expiredBinding, MutationActorUnattributed},
		{"workload channel human uid with valid binding is gated", ChannelWorkload, HumanUID, binding, MutationActorUnattributed},
		{"guest-supervisor workload uid with nil binding", ChannelGuestSupervisor, WorkloadUID, nil, MutationActorAgent},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if got := MutationActorForRecord(tc.channel, tc.uid, tc.binding, now); got != tc.want {
				t.Errorf("MutationActorForRecord(%q, %d) = %q, want %q", tc.channel, tc.uid, got, tc.want)
			}
		})
	}
}

// TestMediatedMutationRejectsIncompleteContract ensures every mutable FUSE
// candidate names its source-derived operation, open mode, relative path, and
// positional semantics before it can enter the recorder.
func TestMediatedMutationRejectsIncompleteContract(t *testing.T) {
	ev := Event{
		Name: EventWorkspaceMutated,
		Attrs: map[string]any{
			AttrMutationUID:          int64(HumanUID),
			AttrMutationOpenerUID:    int64(HumanUID),
			AttrMutationBasis:        "caller",
			AttrMutationActorClass:   string(MutationActorHuman),
			AttrMutationOpenMode:     string(MutationOpenReadWrite),
			AttrMutationOperation:    string(MutationOperationWrite),
			AttrMutationPath:         "notes.txt",
			AttrMutationPosition:     int64(0),
			AttrMutationPositionKind: string(MutationPositionPositional),
			AttrContentDigest:        SHA256Hex([]byte("bounded content")),
		},
	}
	if err := ev.Validate(); err != nil {
		t.Fatalf("Validate complete mutation: %v", err)
	}
	delete(ev.Attrs, AttrMutationPositionKind)
	if err := ev.Validate(); err == nil {
		t.Fatal("Validate incomplete mutation = nil, want error")
	}
}

func TestMediatedMutationRejectsWorkspaceRootEscape(t *testing.T) {
	ev := Event{
		Name: EventWorkspaceMutated,
		Attrs: map[string]any{
			AttrMutationUID:          int64(HumanUID),
			AttrMutationOpenerUID:    int64(HumanUID),
			AttrMutationBasis:        "caller",
			AttrMutationActorClass:   string(MutationActorHuman),
			AttrMutationOpenMode:     string(MutationOpenReadWrite),
			AttrMutationOperation:    string(MutationOperationWrite),
			AttrMutationPath:         "..",
			AttrMutationPosition:     int64(0),
			AttrMutationPositionKind: string(MutationPositionPositional),
			AttrContentDigest:        SHA256Hex([]byte("bounded content")),
		},
	}
	if err := ev.Validate(); err == nil {
		t.Fatal("Validate workspace-root escape = nil, want error")
	}
}
